# Generated by Django 4.1.4 on 2023-05-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('abbr', models.CharField(max_length=10, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='LevelCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('level_number', models.IntegerField(verbose_name='Номер')),
                ('сorse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corses.corses', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='ThemesLevelCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название темы')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('is_author', models.BooleanField(verbose_name='Авторская тема?')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corses.levelcourses', verbose_name='Уровень')),
            ],
        ),
    ]
